---
- name: Create the directory structure where the custom facts are stored
  hosts: all
  become: true
  vars:
    remote_folder: /etc/ansible/facts.d
    file: custom.fact
  tasks:
  - name: create the directory
    file: 
      state: directory
      recurse: true
      path: "{{ remote_folder }}"
  - name: Copy the custom.fact 
    copy:
      src: "{{ file }}"
      dest: "{{ remote_folder }}"
...
