---
- name: Using register variables
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Print task1
    shell: "echo This is my item: {{ item }}"
    loop:
    - one
    - two
    register: echo_results
  - name: Show the output 
    debug:
      var: echo_results
...
