---
- name: Set the mode 
  hosts: all
  become: true
  vars:
    selinux_state: enforcing
  tasks:
  - name: Set the mode using roles 
    block:
    - include_role: 
       name: rhel-system-roles.selinux
    rescue:
    - name: Reboot 
      reboot: 
...
